# Generated by Django 3.1.5 on 2021-02-13 06:33

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='context',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
